// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using uppgift2.service.Data;

#nullable disable

namespace uppgift2.service.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("uppgift2.service.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "J.K. Rowling",
                            ISBN = "978-91-29-65843-7",
                            Pages = 335,
                            PublishedYear = 1997,
                            Title = "Harry Potter och De vises sten"
                        },
                        new
                        {
                            Id = 2,
                            Author = "J.R.R. Tolkien",
                            ISBN = "978-91-0-012345-6",
                            Pages = 423,
                            PublishedYear = 1954,
                            Title = "Sagan om ringen: Härskarringen"
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            ISBN = "978-91-7011-234-5",
                            Pages = 328,
                            PublishedYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jane Austen",
                            ISBN = "978-91-0-011122-3",
                            Pages = 432,
                            PublishedYear = 1813,
                            Title = "Stolthet och fördom"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Suzanne Collins",
                            ISBN = "978-91-7429-123-4",
                            Pages = 374,
                            PublishedYear = 2008,
                            Title = "Hungerspelen"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Astrid Lindgren",
                            ISBN = "978-91-29-65432-1",
                            Pages = 224,
                            PublishedYear = 1973,
                            Title = "Bröderna Lejonhjärta"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Astrid Lindgren",
                            ISBN = "978-91-29-65111-2",
                            Pages = 156,
                            PublishedYear = 1946,
                            Title = "Mästerdetektiven Blomkvist"
                        },
                        new
                        {
                            Id = 8,
                            Author = "J.R.R. Tolkien",
                            ISBN = "978-91-0-012222-2",
                            Pages = 310,
                            PublishedYear = 1937,
                            Title = "Hobbit"
                        });
                });

            modelBuilder.Entity("uppgift2.service.Models.BookCopy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("CopyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BookCopies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            CopyNumber = "HP-001"
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
                            CopyNumber = "HP-002"
                        },
                        new
                        {
                            Id = 3,
                            BookId = 1,
                            CopyNumber = "HP-003"
                        },
                        new
                        {
                            Id = 4,
                            BookId = 2,
                            CopyNumber = "LOTR-001"
                        },
                        new
                        {
                            Id = 5,
                            BookId = 2,
                            CopyNumber = "LOTR-002"
                        },
                        new
                        {
                            Id = 6,
                            BookId = 3,
                            CopyNumber = "1984-001"
                        },
                        new
                        {
                            Id = 7,
                            BookId = 3,
                            CopyNumber = "1984-002"
                        },
                        new
                        {
                            Id = 8,
                            BookId = 4,
                            CopyNumber = "PP-001"
                        },
                        new
                        {
                            Id = 9,
                            BookId = 5,
                            CopyNumber = "HG-001"
                        },
                        new
                        {
                            Id = 10,
                            BookId = 5,
                            CopyNumber = "HG-002"
                        },
                        new
                        {
                            Id = 11,
                            BookId = 5,
                            CopyNumber = "HG-003"
                        },
                        new
                        {
                            Id = 12,
                            BookId = 6,
                            CopyNumber = "BL-001"
                        },
                        new
                        {
                            Id = 13,
                            BookId = 6,
                            CopyNumber = "BL-002"
                        },
                        new
                        {
                            Id = 14,
                            BookId = 7,
                            CopyNumber = "MB-001"
                        },
                        new
                        {
                            Id = 15,
                            BookId = 8,
                            CopyNumber = "HOB-001"
                        },
                        new
                        {
                            Id = 16,
                            BookId = 8,
                            CopyNumber = "HOB-002"
                        });
                });

            modelBuilder.Entity("uppgift2.service.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookCopyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoanDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookCopyId");

                    b.HasIndex("UserId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookCopyId = 1,
                            LoanDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookCopyId = 4,
                            LoanDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            BookCopyId = 9,
                            LoanDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            BookCopyId = 6,
                            LoanDate = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            BookCopyId = 2,
                            LoanDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            BookCopyId = 5,
                            LoanDate = new DateTime(2024, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            BookCopyId = 10,
                            LoanDate = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            BookCopyId = 12,
                            LoanDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            BookCopyId = 15,
                            LoanDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            BookCopyId = 8,
                            LoanDate = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            BookCopyId = 3,
                            LoanDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 12,
                            BookCopyId = 11,
                            LoanDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 13,
                            BookCopyId = 13,
                            LoanDate = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            BookCopyId = 1,
                            LoanDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            Id = 15,
                            BookCopyId = 9,
                            LoanDate = new DateTime(2024, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            Id = 16,
                            BookCopyId = 16,
                            LoanDate = new DateTime(2024, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            Id = 17,
                            BookCopyId = 6,
                            LoanDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5
                        },
                        new
                        {
                            Id = 18,
                            BookCopyId = 14,
                            LoanDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5
                        },
                        new
                        {
                            Id = 19,
                            BookCopyId = 2,
                            LoanDate = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5
                        });
                });

            modelBuilder.Entity("uppgift2.service.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MemberSince")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "anna@example.com",
                            MemberSince = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Anna Andersson"
                        },
                        new
                        {
                            Id = 2,
                            Email = "erik@example.com",
                            MemberSince = new DateTime(2019, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Erik Eriksson"
                        },
                        new
                        {
                            Id = 3,
                            Email = "maria@example.com",
                            MemberSince = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maria Svensson"
                        },
                        new
                        {
                            Id = 4,
                            Email = "johan@example.com",
                            MemberSince = new DateTime(2020, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Johan Karlsson"
                        },
                        new
                        {
                            Id = 5,
                            Email = "lisa@example.com",
                            MemberSince = new DateTime(2022, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lisa Nilsson"
                        });
                });

            modelBuilder.Entity("uppgift2.service.Models.BookCopy", b =>
                {
                    b.HasOne("uppgift2.service.Models.Book", "Book")
                        .WithMany("Copies")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("uppgift2.service.Models.Loan", b =>
                {
                    b.HasOne("uppgift2.service.Models.BookCopy", "BookCopy")
                        .WithMany("Loans")
                        .HasForeignKey("BookCopyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("uppgift2.service.Models.User", "User")
                        .WithMany("Loans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookCopy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("uppgift2.service.Models.Book", b =>
                {
                    b.Navigation("Copies");
                });

            modelBuilder.Entity("uppgift2.service.Models.BookCopy", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("uppgift2.service.Models.User", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
